package br.com.cadastro.util;

import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;

import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;

import br.com.cadastro.dao.RelatoriosDao;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperRunManager;

public class GerarReport2  {
	public ResultSet resultSet(String sql) throws SQLException {
		RelatoriosDao dao = new RelatoriosDao();
		Connection conexao = dao.getConnection();
		Statement st = conexao.createStatement();
		return st.executeQuery(sql);
	}

	public void geraRelatorio(String arquivo) throws JRException, Exception {
		ServletOutputStream servlet = null;
		FacesContext context = FacesContext.getCurrentInstance();
		HttpServletResponse response = (HttpServletResponse) context.getExternalContext().getResponse();
		
		try {
			servlet = response.getOutputStream();
			JasperRunManager.runReportToPdfStream(new FileInputStream(new File(arquivo)), servlet, null);
			
		}catch (Exception e) {
			// TODO: handle exception
		}
		
		
	}
	
	
}
